---
- hosts: localhost
  become: true
  vars:
    bip: "systemctl status docker.service | grep dns"
  tasks:
    - name: "Only apply on machines that have dnsmasq listening on docker interface"
      meta: end_play
      when: ansible_fqdn != ansible_env.WORK_PC1F

    - name: "Set docker DNS config"
      copy:
        dest: "/etc/systemd/system/docker.service.d/99-dns.conf"
        content: |
                 [Service]
                 ExecStart=
                 ExecStart=/usr/bin/dockerd -H unix:// --dns 172.17.0.1

    - name: "Restart Docker service"
      service:
        name: docker
        state: restarted
        daemon_reload: yes
