---
- hosts: localhost
  become: true
  tasks:
    - name: Ensure Dvorak
      lineinfile:
        path:   /etc/default/keyboard
        regexp: "{{ item.regexp }}"
        line:   "{{ item.line }}"
      with_items:
      - regexp: '^XKBLAYOUT='
        line:   'XKBLAYOUT="us"'
      - regexp: '^XKBMODEL='
        line:   'XKBMODEL="pc105"'
      - regexp: '^XKBVARIANT='
        line:   'XKBVARIANT="dvp"'
      - regexp: '^XKBOPTIONS='
        line:   'XKBOPTIONS=""'
      - regexp: '^BACKSPACE='
        line:   'BACKSPACE="guess"'
      register: dvorak
