## vimf6_ansible_args: --diff 
## vimf6_ansible_args: --diff -e zabbix_env=uat -i inventory.yml --vault-id dev@secrets/ansible-vault-dev --vault-id prod@secrets/ansible-vault-prod
## vimf6_ansible_args: --diff --check -vv
## vimf6_ansible_args: --diff -i ./.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
## vimf6_ansible_env: display_skipped_hosts = yes
## vimf6_ansible_env: display_ok_hosts = yes
## vimf6_ansible_nolocalsudo: no
## vimf6_ansible_args: --diff
## vimf6_ansible_nolocalsudo: yes
- hosts: localhost
  vars:
    source: "https://askubuntu.com/questions/1081695/error-during-converting-jpg-to-pdf"
  become: true
  tasks:
    - name: "Fix Image Magick JPG to PDF conversion"
      xml:
        path: "/etc/ImageMagick-6/policy.xml"
        xpath: "/policymap/policy[@pattern='PDF']"
        attribute: rights
        value: "read|write"
