---
- hosts: localhost
  become: true
  tasks:
    - name: apt update + upgrade
      apt:
        #autoremove: yes
        #upgrade: 'safe'
        cache_valid_time: 86400
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: apt install
      apt:
        name:
          - gpick
          - jq
          - ack-grep
          - keepassxc
          - i3lock
          - unattended-upgrades
          - python-backports.ssl-match-hostname # ansible docker module for python2
          - redshift
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
