# ex: set filetype=yaml fenc=utf-8 expandtab ts=2 sw=2 :
## vimf6_ansible_args: --diff
## vimf6_ansible_nolocalsudo: no
---
- hosts: localhost
  become: false
  vars:
    mruser: "{{ ansible_env.SUDO_USER }}"
  tasks:
    - name: Reset ownership beforehand
      changed_when: false
      args:
        warn: no
      shell: >
        bash -c 'chown -R {{ mruser }}: ~{{ mruser }}/.local/{bin,lib/python*}'

    - name: "Python3 Python 2+3 system pip"
      apt:
        name:
        - "python-pip"
        - "python3-pip"
      become: true

    - name: stat ~/.local/bin/pip2
      become: "{{ mruser }}"
      stat:
        path: ~/.local/bin/pip2
      register: stat2_result
      become: false

    - name: "Python2 install user pip2"
      become: "{{ mruser }}"
      pip:
        name:
        - pip
        executable: /usr/bin/pip2
        extra_args: --user
      when: stat2_result.stat.exists == False

    - name: "Python2 upgrade user pip"
      become: "{{ mruser }}"
      pip:
        name:
        - pip
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip2
      when: stat2_result.stat.exists == True

    - name: "Python2 ensure packages latest"
      become: "{{ mruser }}"
      pip:
        name:
        - youtube_dl
        - i3ipc
        - future
        # - packaging # ansible azure
        - ansible[azure]
        - azure
        # websupport/search.py
        - LatLon
        # BeautifulSoup
        - bs4
        # expect_kpcli.py
        - pexpect
        # netcalc
        - netcalc
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip2

    - name: "Python2 ensure packages present"
      become: "{{ mruser }}"
      pip:
        name:
        - sh
        extra_args: --user
        executable: ~/.local/bin/pip2

    - name: stat ~/.local/bin/pip3
      become: "{{ mruser }}"
      stat:
        path: ~/.local/bin/pip3
      register: stat3_result

    - debug: var=stat3_result

    - name: "Python3 install user pip3"
      become: "{{ mruser }}"
      pip:
        name:
        - pip
        extra_args: --user
        executable: /usr/bin/pip3
      when: not stat3_result.stat.exists

    - name: "Python3 upgrade user pip"
      become: "{{ mruser }}"
      pip:
        name:
        - pip
        extra_args: --upgrade --user
        executable: "{{ '~/.local/bin/pip3' if stat3_result.stat.exists else '/usr/bin/pip3' }}"

    - name: "Python3 ensure packages latest"
      become: "{{ mruser }}"
      pip:
        name:
        - youtube_dl
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip3

    - name: "Python3 ensure packages present"
      become: "{{ mruser }}"
      pip:
        name:
        - sh
        - fontawesome # mri3server
        - scapy
        - i3ipc
        - lxml
        - zabbix_api
        extra_args: --user
        executable: ~/.local/bin/pip3

    - name: Reset ownership afterwords
      changed_when: false
      args:
        warn: no
      shell: >
        bash -c 'chown -R {{ mruser }}: ~{{ mruser }}/.local/{bin,lib/python*}'
