---
- hosts: localhost
  become: false
  tasks:
    - name: "check if user pip is present"
      stat:
        path: ~/.local/bin/pip2
      register: stat_result

    - name: "install user pip"
      pip:
        name:
        - pip
        extra_args: --user
      when: stat_result.stat.exists == False

    - name: "upgrade user pip"
      pip:
        name:
        - pip
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip2
      when: stat_result.stat.exists == True

    - name: "ensure latest"
      pip:
        name:
        - youtube_dl
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip2

    - name: "ensure present"
      pip:
        name:
        - sh
        extra_args: --user
        executable: ~/.local/bin/pip2
