---
- hosts: localhost
  become: true
  tasks:
  - name: dep
    apt:
      name:
      - libxml2-dev
      - python-dev
      - libxslt1-dev

  - name: "mr pip"
    pip:
      name: lxml
      extra_args: --user
      executable: ~/.local/bin/pip2
