# ex: set filetype=yaml fenc=utf-8 expandtab ts=2 sw=2 :
## vimf6_ansible_args: --diff
## vimf6_ansible_args: --diff --check -vv
## vimf6_ansible_nolocalsudo: no
## vimf6_ansible_nolocalsudo: yes
---
- hosts: localhost
  become: false
  tasks:
    - name: "Python3 Python 2+3 system pip"
      apt:
        name:
        - "python-pip"
        - "python3-pip"
      become: true

    - name: "Python2 check if user is present"
      stat:
        path: ~/.local/bin/pip2
      register: stat2_result
      become: false

    - name: "Python2 install user pip2"
      pip:
        name:
        - pip
        executable: /usr/bin/pip2
        extra_args: --user
      when: stat2_result.stat.exists == False

    - name: "Python2 upgrade user pip"
      pip:
        name:
        - pip
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip2
      when: stat2_result.stat.exists == True

    - name: "Python2 ensure packages latest"
      pip:
        name:
        - youtube_dl
        - i3ipc
        - future
        # - packaging # ansible azure
        - ansible[azure]
        - azure
        # websupport/search.py
        - LatLon
        # BeautifulSoup
        - bs4
        # expect_kpcli.py
        - pexpect
        # netcalc
        - netcalc
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip2

    - name: "Python2 ensure packages present"
      pip:
        name:
        - sh
        extra_args: --user
        executable: ~/.local/bin/pip2

    - name: "Python3 check if user pip3 is present"
      stat:
        path: ~/.local/bin/pip3
      register: stat3_result

    - name: "Python3 install user pip3"
      pip:
        name:
        - pip
        extra_args: --user
        executable: /usr/bin/pip3
      when: stat3_result.stat.exists == False

    - name: "Python3 upgrade user pip"
      pip:
        name:
        - pip
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip3
      when: stat3_result.stat.exists == True

    - name: "Python3 ensure packages latest"
      pip:
        name:
        - youtube_dl
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip3

    - name: "Python3 ensure packages present"
      pip:
        name:
        - sh
        - fontawesome # mri3server
        - i3ipc
        - lxml
        - zabbix_api
        extra_args: --user
        executable: ~/.local/bin/pip3
