# ex: set filetype=yaml fenc=utf-8 expandtab ts=2 sw=2 :
## vimf6_ansible_args: --diff
## vimf6_ansible_args: --diff --start-at-task "Python3 az"
## vimf6_ansible_nolocalsudo: no
---
- hosts: localhost
  become: no
  vars:
    mruser: "{{ ansible_user }}"
    python2: true
  tasks:
    - name: Reset ownership beforehand
      become: true
      changed_when: false
      args:
        warn: no
      shell: >
        bash -c 'chown -R {{ mruser }}: ~{{ mruser }}/.local/{bin,lib/python*}'

    - name: "Python3 Python 2+3 system pip"
      apt:
        name:
        - "python-pip"
        - "python3-pip"
      become: true

    - name: stat ~/.local/bin/pip2
      stat:
        path: ~/.local/bin/pip2
      register: stat2_result

    - name: "Python2 install user pip2"
      pip:
        name:
        - pip
        executable: /usr/bin/pip2
        extra_args: --user
      when: python2 and stat2_result.stat.exists == False

    - name: "Python2 upgrade user pip"
      pip:
        name:
        - pip
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip2
      when: python2 and stat2_result.stat.exists == True

    - name: "Python2 ensure packages latest"
      when: python2
      pip:
        name:
        - youtube_dl
        - i3ipc
        - future
        # websupport/search.py
        - LatLon
        # BeautifulSoup
        - bs4
        # expect_kpcli.py
        - pexpect
        # netcalc
        - netcalc
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip2

    - name: "Python2 ensure packages present"
      when: python2
      pip:
        name:
        - sh
        extra_args: --user
        executable: ~/.local/bin/pip2

    - name: stat ~/.local/bin/pip3
      stat:
        path: ~/.local/bin/pip3
      register: stat3_result

    - debug: var=stat3_result

    - name: "Python3 install user pip3"
      pip:
        name:
        - pip
        extra_args: --user
        executable: /usr/bin/pip3
      when: not stat3_result.stat.exists

    - name: "Python3 upgrade user pip"
      pip:
        name:
        - pip
        extra_args: --upgrade --user
        executable: "{{ '~/.local/bin/pip3' if stat3_result.stat.exists else '/usr/bin/pip3' }}"

    - name: "Python3 ensure packages latest"
      pip:
        name:
        - youtube_dl
        extra_args: --upgrade --user
        executable: ~/.local/bin/pip3

    - name: "Python3 ensure packages absent"
      pip:
        state: absent
        executable: ~/.local/bin/pip3
        name:
          - docker-py

    - name: "Python3 ensure packages present+latest"
      pip:
        name:
        - ansible
        - docker
        - bs4 # beautiful soup 4
        - fahrplan # cff sbb timetable
        - fontawesome # mri3server
        - i3ipc
        - jmespath # ansible json_query filter dependency
        - kubernetes-validate # ansible kubernetes
        - lxml
        - openshift # ansible kubernetes
        - passlib # generate hashes
        - packaging # blobfuse role
        - pyzmail36 # smtp
        - scapy
        - selenium
        - sh
        - zabbix_api
        extra_args: --user
        state: latest
        executable: ~/.local/bin/pip3

    - name: Reset ownership afterwords
      become: true
      changed_when: false
      args:
        warn: no
      shell: >
        bash -c 'chown -R {{ mruser }}: ~{{ mruser }}/.local/{bin,lib/python*}'

    - name: "Python3 az"
      pip:
        name:
        - azure-cli
        state: latest
        virtualenv: ~/.virtualenvs/az-cli

