# ex: set filetype=yaml fenc=utf-8 expandtab ts=2 sw=2 :
## vimf6_ansible_args: --diff
## vimf6_ansible_args: --diff --check -vv
## vimf6_ansible_args: --diff -i ./.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
## vimf6_ansible_nolocalsudo: yes
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Removes snap version (I had problem with ACPI)
      snap:
        name: spotify
        state: absent

    - name: Add external key server
      with_items:
        - 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
        - 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: "{{ item }}"

    - name: Add  external repository
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present

    - name: install from apt
      apt:
        update_cache: yes
        name: spotify-client
        state: present
