---
- hosts: localhost
  become: true
  tasks:
    - name: apt update + upgrade
      apt:
        #autoremove: yes
        #upgrade: 'safe'
        cache_valid_time: 86400
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: apt install
      apt:
        name: 
          - numlockx
        state: present

    - name: numlock set to on on startup
      lineinfile:
        path: /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
        regexp: '^greeter-setup-script='
        line: 'greeter-setup-script=/usr/bin/numlockx on'
