FROM shk3bq4d/stdenv:apt

	#&& pip3 install --upgrade --user pip \
	# && pip install --upgrade --user pip \
RUN true \
	&& pip3 install --user \
		requests \
		sh \
		sshuttle \
		psutil \
	&& pip install --user \
		requests \
		sh \
		sshuttle \
		psutil \
	&& true

