Vagrant.configure("2") do |config|
  # choose user vagrant, password is vagrant
  config.vm.box = "mwrock/Windows2016"
  config.vm.hostname = "vagrant-win"
  config.vm.network "public_network"
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
    v.linked_clone = true
  end
end
